### ISSUE TITLE
Getting an invalid date error when extracting metadata for certain files

### ISSUE THREAD

**Issue by swaathi** [mceachen/exiftool#2]
Here is the log:

``` 2015-02-06T09:56:30.100Z 92320 TID-oxbi4ru1w WARN: invalid date
2015-02-06T09:56:30.101Z 92320 TID-oxbi4ru1w WARN: /Users/karthik/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/exiftool-0.6.0/lib/exiftool/field_parser.rb:33:in `civil'
/Users/karthik/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/exiftool-0.6.0/lib/exiftool/field_parser.rb:33:in `civil_date' ```


And here's the code:

 def filemeta(myfile)
  	return Exiftool.new(oldpath(myfile)).to_hash
end 

I thought this was an EXIFtool error so I tried extracting the metadata using the exiftool system command, and it worked. I wonder where this issue is! Tried Googling for it, and nothing turned up.

**Comment by mceachen** [comment]
Can you upload the image please?

**Comment by swaathi** [comment]
It's a video. Unfortunately the file size is greater than 10MB so GitHub isn't allowing me to upload it here. I'd be happy to mail it to you. The video is actually a Rails cast I downloaded (mp4 version), here it is: http://railscasts.com/episodes/406-public-activity.

**Comment by mceachen** [comment]
Great, thanks. I'll see what's going on here when I get a chance this
weekend.

**Comment by swaathi** [comment]
Sounds great :) I forgot to add, I ended up using your other branch `no_broken_dates`, and that seemed to clear things up.

**Comment by janfoeh** [comment]
I have the same issue; the problematic input seems to be `0000:00:00 00:00:00`.

**Comment by swaathi** [comment]
Have you tried using the branch 'no broken dates'?

Swaathi K
CoFounder, Skcript

**Comment by janfoeh** [comment]
Yes — that fixes it in my case as well.

**Comment by mceachen** [comment]
Thanks for debugging this!

I'll pull that branch as soon as I can. Can one of you export the EXIF
header that broke the code, so we can make a breaking test for this issue
that is fixed by the "no broken dates" branch?

On Tue, Feb 17, 2015 at 1:29 AM, Jan-Christian Föh <notifications@github.com

**Comment by janfoeh** [comment]
Here it is:

    File Name                       : 202.mp4
    Directory                       : /Users/jfoeh/dev/rails/ada/public/system/assets/media/000/000/202/original
    File Size                       : 61 MB
    File Modification Date/Time     : 2015:02:17 10:55:18+01:00
    File Access Date/Time           : 2015:02:17 10:56:44+01:00
    File Inode Change Date/Time     : 2015:02:17 10:55:19+01:00
    File Permissions                : rw-r--r--
    File Type                       : MP4
    MIME Type                       : video/mp4
    Major Brand                     : MP4  Base Media v1 [IS0 14496-12:2003]
    Minor Version                   : 0.2.0
    Compatible Brands               : isom, iso2, avc1, mp41
    Movie Data Size                 : 64258404
    Movie Data Offset               : 48
    Movie Header Version            : 0
    Create Date                     : 0000:00:00 00:00:00
    Modify Date                     : 0000:00:00 00:00:00
    Time Scale                      : 1000
    Duration                        : 0:01:46
    Preferred Rate                  : 1
    Preferred Volume                : 100.00%
    Preview Time                    : 0 s
    Preview Duration                : 0 s
    Poster Time                     : 0 s
    Selection Time                  : 0 s
    Selection Duration              : 0 s
    Current Time                    : 0 s
    Next Track ID                   : 3
    Track Header Version            : 0
    Track Create Date               : 0000:00:00 00:00:00
    Track Modify Date               : 0000:00:00 00:00:00
    Track ID                        : 1
    Track Duration                  : 0:01:46
    Track Layer                     : 0
    Track Volume                    : 0.00%
    Image Width                     : 1024
    Image Height                    : 576
    Graphics Mode                   : srcCopy
    Op Color                        : 0 0 0
    Compressor ID                   : avc1
    Source Image Width              : 1024
    Source Image Height             : 576
    X Resolution                    : 72
    Y Resolution                    : 72
    Bit Depth                       : 24
    Video Frame Rate                : 25
    Matrix Structure                : 1 0 0 0 1 0 0 0 1
    Media Header Version            : 0
    Media Create Date               : 0000:00:00 00:00:00
    Media Modify Date               : 0000:00:00 00:00:00
    Media Time Scale                : 44100
    Media Duration                  : 0:01:46
    Media Language Code             : und
    Handler Description             : SoundHandler
    Balance                         : 0
    Audio Format                    : mp4a
    Audio Channels                  : 2
    Audio Bits Per Sample           : 16
    Audio Sample Rate               : 44100
    Handler Type                    : Metadata
    Handler Vendor ID               : Apple
    Encoder                         : Lavf56.15.102
    Avg Bitrate                     : 4.83 Mbps
    Image Size                      : 1024x576
    Rotation                        : 0

**Comment by mceachen** [comment]
Great, thanks.

**Comment by teemujonkkari** [comment]
> I have the same issue; the problematic input seems to be 0000:00:00 00:00:00.

I'm using exiftool 0.6.0 (gem) and the same date problem still occurs with jpeg files. 

Exiftool version is 9.76.

**Comment by morozgrafix** [comment]
@teemujonkkari I've created a [fork that handles dates](https://github.com/morozgrafix/exiftool) that are set to `0000:00:00` which I found to be produced by my scanner software. It should also handle `0000:00:00 00:00:00` dates without any errors

@mceachen let me know if it's worth a PR

**Comment by mceachen** [comment]
If you make a PR, that's be great!

**Comment by morozgrafix** [comment]
@mceachen I've made a PR but looks like travis-ci tests are running with 4 year old version of exiftool v.8.60 ¯\_(ツ)_/¯

**Comment by mceachen** [comment]
Thanks for the PR! I just released v0.7.0 with the fix.

**Comment by morozgrafix** [comment]
:+1: :bow:
